import { describe, it, expect, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import en from '@/lib/translations/en.json'

const lookup = (key: string): string =>
  key.split('.').reduce<unknown>((node, part) => (node as Record<string, unknown> | undefined)?.[part], en) as string

vi.mock('@/contexts/language-context', () => ({ useLanguage: () => ({ t: lookup, language: 'en' }) }))
vi.mock('@/components/layout/header', () => ({ Header: () => null }))
vi.mock('@/components/sections/footer', () => ({ Footer: () => null }))
vi.mock('next/navigation', () => ({ useRouter: () => ({ push: vi.fn() }), useSearchParams: () => new URLSearchParams() }))
vi.mock('@/lib/api', () => ({ apiService: { post: vi.fn() }, default: { get: vi.fn(), post: vi.fn() } }))

import { WaysToEarn } from './ways-to-earn'
import { Features } from './features'
import { FAQ } from './faq'
import ClubsPage from '@/app/clubs/page'
import ContactPage from '@/app/contact/page'
import AboutPage from '@/app/about/page'
import AboutMobilePage from '@/app/pages_mobile/about/page'
import AboutNestedMobilePage from '@/app/about/pages_mobile/about/page'
import sitemap from '@/app/sitemap'
import { ABOUT_TEAM_MEMBERS, publishedTeamMembers } from '@/lib/about-team'

describe('landing page content (confirmed wording)', () => {
  it('uses the confirmed affiliate and category wording', () => {
    const { container } = render(<Features />)
    const text = container.textContent ?? ''
    expect(text).toContain('Earn affiliate commission on the revenue generated by your direct referrals.')
    expect(text).toContain('Beauty, Handsomeness, Comedy, Music, Pets, Sports Clubs, and much more.')
    expect(text).not.toMatch(/referral network|Latest Hits/)
  })

  it('has no Referral Pool, Club or Shop earning card and keeps the Leaders program', () => {
    const { container } = render(<WaysToEarn />)
    const text = container.textContent ?? ''
    expect(text).not.toMatch(/Referral Pool|\$100|assigned new members/i)
    expect(text).not.toMatch(/Club Memberships|paid clubs/i)
    expect(text).not.toMatch(/Shop Purchases|digital purchases/i)  // marketplace is disabled
    expect(text).toContain(en.landing.ways_to_earn.leaders.title)
  })

  it('states the confirmed direct affiliate rule and the permanent 40% qualification', () => {
    const { container } = render(<WaysToEarn />)
    const text = container.textContent ?? ''
    expect(text).toContain(
      'Earn 20% of the website revenue generated by the members you directly refer, plus additional rewards from the MyHigh5 Leaders Program.',
    )
    expect(text).toMatch(/10,000 direct referrals who complete KYC verification within six months of your joining date/)
    expect(text).toMatch(/increases permanently to 40%/)
  })

  it('distinguishes ad-slot commission, contest-page sharing and Annual Ads with the confirmed percentages', () => {
    render(<WaysToEarn />)
    const slots = en.landing.ways_to_earn.ad_campaigns
    const page = en.landing.ways_to_earn.ad_revenue
    expect(screen.getByText(slots.title)).toBeInTheDocument()
    expect(screen.getByText(page.title)).toBeInTheDocument()
    expect(slots.description).toMatch(/20% of the full ad-slot price, or 40% once you have permanently qualified/)
    expect(slots.description).toMatch(/Annual Ads earn this direct-referral commission only/)
    expect(page.description).toMatch(/Personal submission \(starting at City level\): you receive 20%.*extra 1%/)
    expect(page.description).toMatch(/Nomination \(starting at Country level\): the nominated creative receives 10%.*extra 1%/)
    expect(page.description).toMatch(/stays with the creative at every later contest level/)
    expect(page.description).toMatch(/Annual Ads are not included in contest-page revenue sharing/)
    expect(`${slots.description} ${page.description}`).not.toMatch(/21%|11%|60%/)
  })

  it('has no Referral Pool question in the FAQ', () => {
    const { container } = render(<FAQ />)
    expect(container.textContent ?? '').not.toMatch(/Referral Pool/i)
  })
})

describe('unfinished Clubs feature is hidden', () => {
  it('shows an unavailable notice instead of the demo preview and the Create-your-own-Club promotion', () => {
    const { container } = render(<ClubsPage />)
    expect(screen.getByText(en.pages.clubs.unavailable_title)).toBeInTheDocument()
    const text = container.textContent ?? ''
    expect(text).not.toMatch(/Create your own Club|Create my Club|Coming soon|Elite Beauty Club/i)
  })

  it('is not listed in the sitemap', () => {
    expect(sitemap().some((entry) => entry.url.endsWith('/clubs'))).toBe(false)
  })
})

describe('Contact page', () => {
  it('uses the confirmed participation wording and keeps nomination vs personal submission distinct', () => {
    const { container } = render(<ContactPage />)
    const text = container.textContent ?? ''
    expect(text).toContain(
      'Create an account and complete your profile. You can then nominate your favorite creatives by submitting them to participate in contests starting at the country level.',
    )
    expect(text).toContain(
      'If you want to participate personally by submitting your own creative, your entry will start at the city level. You must first verify your account before submitting your own creative.',
    )
    expect(text).not.toMatch(/Fan Club|Create a Club/i)
  })
})

describe('About page team', () => {
  it.each([
    ['desktop', AboutPage],
    ['mobile', AboutMobilePage],
    ['mobile (about/)', AboutNestedMobilePage],
  ])('%s: founder plus Md Shakil Ahsan as Director of ICT; Morice is gone', (_label, Page) => {
    const { container } = render(<Page />)
    const text = container.textContent ?? ''
    expect(text).toContain('Shafi Kaluta Abedi')
    expect(text).toContain('Founder and President')
    expect(text).toContain('Md Shakil Ahsan')
    expect(text).toContain('Director of ICT')
    expect(text).not.toMatch(/Morice|Wangwe/)
    expect(container.querySelector('img[src*="morice"]')).toBeNull()
    const photo = screen.getByAltText('Md Shakil Ahsan - Director of ICT')
    expect(photo).toHaveAttribute('src', '/team/md-shakil-ahsan.jpg')
    expect(photo.className).toMatch(/object-cover/)  // cropped to the round frame, never stretched
    expect(photo.className).toMatch(/w-full h-full/)
    expect(container.querySelector('.md\\:grid-cols-2')).not.toBeNull()  // two members: two columns from md up
  })

  it('publishes the authorised profile from one shared list', () => {
    expect(ABOUT_TEAM_MEMBERS.find((m) => m.name === 'Md Shakil Ahsan')).toEqual({
      name: 'Md Shakil Ahsan', roleKey: 'team.director_ict', image: '/team/md-shakil-ahsan.jpg', published: true,
    })
    expect(publishedTeamMembers().map((m) => m.name)).toEqual(['Shafi Kaluta Abedi', 'Md Shakil Ahsan'])
  })
})
