"""Texts of the KYC and contest status emails (EMAIL-3), in the four primary
email languages. Merged into email_templates.EMAIL_TRANSLATIONS; any other
language falls back to English there.

`{entry}` and `{contest}` are filled by the template helper, which escapes
them for HTML. Every text describes a state the application has already
committed; none promises voting, ranking or a result.
"""

_BUTTON_ENTRIES = {"fr": "Voir mes candidatures", "en": "View my entries", "es": "Ver mis participaciones",
                   "de": "Meine Einträge ansehen"}

EVENT_TEXTS = {
    "en": {
        "entries_button": _BUTTON_ENTRIES["en"],
        "nomination_published_subject": "Your nomination is published - MyHigh5",
        "nomination_published_title": "Your nomination is published",
        "nomination_published_message": "Your nomination <strong>{entry}</strong> in <strong>{contest}</strong> is now public on MyHigh5.",
        "nomination_published_note": "Voting opens when the contest reaches its voting stage.",
        "nomination_removed_subject": "Your nomination has been removed - MyHigh5",
        "nomination_removed_title": "Your nomination has been removed",
        "nomination_removed_message": "Following a review by our team, your nomination <strong>{entry}</strong> in <strong>{contest}</strong> is no longer shown on MyHigh5.",
        "nomination_removed_note": "If you think this is a mistake, please contact our support team.",
        "nomination_action_subject": "Update requested for your nomination - MyHigh5",
        "nomination_action_title": "An update is requested for your nomination",
        "nomination_action_message": "Our team has asked for an update to your nomination <strong>{entry}</strong> in <strong>{contest}</strong>.",
        "nomination_action_note": "Open your entries to see what is needed and update the nomination.",
        "participation_pending_subject": "We received your entry - MyHigh5",
        "participation_pending_title": "We received your entry",
        "participation_pending_message": "Your entry <strong>{entry}</strong> in <strong>{contest}</strong> has been received. It is not public yet: it is being checked.",
        "participation_pending_note": "You can follow its status, and any step expected from you, in your entries.",
        "participation_published_subject": "Your entry is published - MyHigh5",
        "participation_published_title": "Your entry is published",
        "participation_published_message": "Your entry <strong>{entry}</strong> in <strong>{contest}</strong> is now public on MyHigh5.",
        "participation_published_note": "Voting opens when the contest reaches its voting stage.",
        "participation_action_subject": "Update required for your entry - MyHigh5",
        "participation_action_title": "An update is required for your entry",
        "participation_action_message": "Our team has asked for an update to your entry <strong>{entry}</strong> in <strong>{contest}</strong>. It stays private until it is updated and checked again.",
        "participation_action_note": "Open your entries to see what is needed and update the entry.",
        "participation_rejected_subject": "Your entry was not accepted - MyHigh5",
        "participation_rejected_title": "Your entry was not accepted",
        "participation_rejected_message": "Following a review by our team, your entry <strong>{entry}</strong> in <strong>{contest}</strong> is not shown on MyHigh5.",
        "participation_rejected_note": "If you think this is a mistake, please contact our support team.",
        "creative_unavailable_subject": "Your video link is no longer available - MyHigh5",
        "creative_unavailable_title": "Your video link is no longer available",
        "creative_unavailable_message": "The video linked to <strong>{entry}</strong> in <strong>{contest}</strong> can no longer be found at its address, so the entry is no longer shown on MyHigh5.",
        "creative_unavailable_note": "If the video was moved or made private by mistake, please contact our support team.",
        "kyc_action_subject": "One more step to complete your verification - MyHigh5",
        "kyc_action_title": "One more step to complete your verification",
        "kyc_action_message": "Your identity check was successful. To complete your verification, please provide a proof of address.",
        "kyc_action_button": "Continue my verification",
    },
    "fr": {
        "entries_button": _BUTTON_ENTRIES["fr"],
        "nomination_published_subject": "Votre nomination est publiée - MyHigh5",
        "nomination_published_title": "Votre nomination est publiée",
        "nomination_published_message": "Votre nomination <strong>{entry}</strong> dans <strong>{contest}</strong> est maintenant publique sur MyHigh5.",
        "nomination_published_note": "Le vote ouvrira lorsque le concours atteindra sa phase de vote.",
        "nomination_removed_subject": "Votre nomination a été retirée - MyHigh5",
        "nomination_removed_title": "Votre nomination a été retirée",
        "nomination_removed_message": "Après examen par notre équipe, votre nomination <strong>{entry}</strong> dans <strong>{contest}</strong> n'est plus affichée sur MyHigh5.",
        "nomination_removed_note": "Si vous pensez qu'il s'agit d'une erreur, veuillez contacter notre support.",
        "nomination_action_subject": "Mise à jour demandée pour votre nomination - MyHigh5",
        "nomination_action_title": "Une mise à jour est demandée pour votre nomination",
        "nomination_action_message": "Notre équipe a demandé une mise à jour de votre nomination <strong>{entry}</strong> dans <strong>{contest}</strong>.",
        "nomination_action_note": "Ouvrez vos candidatures pour voir ce qui est attendu et mettre la nomination à jour.",
        "participation_pending_subject": "Nous avons bien reçu votre candidature - MyHigh5",
        "participation_pending_title": "Nous avons bien reçu votre candidature",
        "participation_pending_message": "Votre candidature <strong>{entry}</strong> dans <strong>{contest}</strong> a bien été reçue. Elle n'est pas encore publique : elle est en cours de vérification.",
        "participation_pending_note": "Vous pouvez suivre son statut, et toute étape attendue de votre part, dans vos candidatures.",
        "participation_published_subject": "Votre candidature est publiée - MyHigh5",
        "participation_published_title": "Votre candidature est publiée",
        "participation_published_message": "Votre candidature <strong>{entry}</strong> dans <strong>{contest}</strong> est maintenant publique sur MyHigh5.",
        "participation_published_note": "Le vote ouvrira lorsque le concours atteindra sa phase de vote.",
        "participation_action_subject": "Mise à jour requise pour votre candidature - MyHigh5",
        "participation_action_title": "Une mise à jour est requise pour votre candidature",
        "participation_action_message": "Notre équipe a demandé une mise à jour de votre candidature <strong>{entry}</strong> dans <strong>{contest}</strong>. Elle reste privée jusqu'à sa mise à jour et une nouvelle vérification.",
        "participation_action_note": "Ouvrez vos candidatures pour voir ce qui est attendu et mettre la candidature à jour.",
        "participation_rejected_subject": "Votre candidature n'a pas été acceptée - MyHigh5",
        "participation_rejected_title": "Votre candidature n'a pas été acceptée",
        "participation_rejected_message": "Après examen par notre équipe, votre candidature <strong>{entry}</strong> dans <strong>{contest}</strong> n'est pas affichée sur MyHigh5.",
        "participation_rejected_note": "Si vous pensez qu'il s'agit d'une erreur, veuillez contacter notre support.",
        "creative_unavailable_subject": "Le lien de votre vidéo n'est plus disponible - MyHigh5",
        "creative_unavailable_title": "Le lien de votre vidéo n'est plus disponible",
        "creative_unavailable_message": "La vidéo liée à <strong>{entry}</strong> dans <strong>{contest}</strong> est introuvable à son adresse ; la candidature n'est donc plus affichée sur MyHigh5.",
        "creative_unavailable_note": "Si la vidéo a été déplacée ou rendue privée par erreur, veuillez contacter notre support.",
        "kyc_action_subject": "Encore une étape pour terminer votre vérification - MyHigh5",
        "kyc_action_title": "Encore une étape pour terminer votre vérification",
        "kyc_action_message": "La vérification de votre identité a réussi. Pour terminer votre vérification, veuillez fournir un justificatif de domicile.",
        "kyc_action_button": "Continuer ma vérification",
    },
    "es": {
        "entries_button": _BUTTON_ENTRIES["es"],
        "nomination_published_subject": "Tu nominación está publicada - MyHigh5",
        "nomination_published_title": "Tu nominación está publicada",
        "nomination_published_message": "Tu nominación <strong>{entry}</strong> en <strong>{contest}</strong> ya es pública en MyHigh5.",
        "nomination_published_note": "La votación se abrirá cuando el concurso llegue a su fase de votación.",
        "nomination_removed_subject": "Tu nominación ha sido retirada - MyHigh5",
        "nomination_removed_title": "Tu nominación ha sido retirada",
        "nomination_removed_message": "Tras una revisión de nuestro equipo, tu nominación <strong>{entry}</strong> en <strong>{contest}</strong> ya no se muestra en MyHigh5.",
        "nomination_removed_note": "Si crees que se trata de un error, ponte en contacto con nuestro soporte.",
        "nomination_action_subject": "Se solicita una actualización de tu nominación - MyHigh5",
        "nomination_action_title": "Se solicita una actualización de tu nominación",
        "nomination_action_message": "Nuestro equipo ha solicitado una actualización de tu nominación <strong>{entry}</strong> en <strong>{contest}</strong>.",
        "nomination_action_note": "Abre tus participaciones para ver qué se necesita y actualizar la nominación.",
        "participation_pending_subject": "Hemos recibido tu participación - MyHigh5",
        "participation_pending_title": "Hemos recibido tu participación",
        "participation_pending_message": "Tu participación <strong>{entry}</strong> en <strong>{contest}</strong> ha sido recibida. Aún no es pública: se está comprobando.",
        "participation_pending_note": "Puedes seguir su estado, y cualquier paso que se espere de ti, en tus participaciones.",
        "participation_published_subject": "Tu participación está publicada - MyHigh5",
        "participation_published_title": "Tu participación está publicada",
        "participation_published_message": "Tu participación <strong>{entry}</strong> en <strong>{contest}</strong> ya es pública en MyHigh5.",
        "participation_published_note": "La votación se abrirá cuando el concurso llegue a su fase de votación.",
        "participation_action_subject": "Se requiere una actualización de tu participación - MyHigh5",
        "participation_action_title": "Se requiere una actualización de tu participación",
        "participation_action_message": "Nuestro equipo ha solicitado una actualización de tu participación <strong>{entry}</strong> en <strong>{contest}</strong>. Seguirá siendo privada hasta que se actualice y se compruebe de nuevo.",
        "participation_action_note": "Abre tus participaciones para ver qué se necesita y actualizarla.",
        "participation_rejected_subject": "Tu participación no ha sido aceptada - MyHigh5",
        "participation_rejected_title": "Tu participación no ha sido aceptada",
        "participation_rejected_message": "Tras una revisión de nuestro equipo, tu participación <strong>{entry}</strong> en <strong>{contest}</strong> no se muestra en MyHigh5.",
        "participation_rejected_note": "Si crees que se trata de un error, ponte en contacto con nuestro soporte.",
        "creative_unavailable_subject": "El enlace de tu vídeo ya no está disponible - MyHigh5",
        "creative_unavailable_title": "El enlace de tu vídeo ya no está disponible",
        "creative_unavailable_message": "El vídeo enlazado a <strong>{entry}</strong> en <strong>{contest}</strong> ya no se encuentra en su dirección, por lo que la participación ya no se muestra en MyHigh5.",
        "creative_unavailable_note": "Si el vídeo se movió o se hizo privado por error, ponte en contacto con nuestro soporte.",
        "kyc_action_subject": "Un paso más para completar tu verificación - MyHigh5",
        "kyc_action_title": "Un paso más para completar tu verificación",
        "kyc_action_message": "La comprobación de tu identidad se ha realizado correctamente. Para completar tu verificación, aporta un justificante de domicilio.",
        "kyc_action_button": "Continuar mi verificación",
    },
    "de": {
        "entries_button": _BUTTON_ENTRIES["de"],
        "nomination_published_subject": "Ihre Nominierung ist veröffentlicht - MyHigh5",
        "nomination_published_title": "Ihre Nominierung ist veröffentlicht",
        "nomination_published_message": "Ihre Nominierung <strong>{entry}</strong> in <strong>{contest}</strong> ist jetzt auf MyHigh5 öffentlich sichtbar.",
        "nomination_published_note": "Die Abstimmung beginnt, sobald der Wettbewerb seine Abstimmungsphase erreicht.",
        "nomination_removed_subject": "Ihre Nominierung wurde entfernt - MyHigh5",
        "nomination_removed_title": "Ihre Nominierung wurde entfernt",
        "nomination_removed_message": "Nach einer Prüfung durch unser Team wird Ihre Nominierung <strong>{entry}</strong> in <strong>{contest}</strong> nicht mehr auf MyHigh5 angezeigt.",
        "nomination_removed_note": "Wenn Sie dies für einen Fehler halten, wenden Sie sich bitte an unseren Support.",
        "nomination_action_subject": "Aktualisierung Ihrer Nominierung angefordert - MyHigh5",
        "nomination_action_title": "Für Ihre Nominierung wird eine Aktualisierung angefordert",
        "nomination_action_message": "Unser Team hat eine Aktualisierung Ihrer Nominierung <strong>{entry}</strong> in <strong>{contest}</strong> angefordert.",
        "nomination_action_note": "Öffnen Sie Ihre Einträge, um zu sehen, was benötigt wird, und aktualisieren Sie die Nominierung.",
        "participation_pending_subject": "Wir haben Ihren Beitrag erhalten - MyHigh5",
        "participation_pending_title": "Wir haben Ihren Beitrag erhalten",
        "participation_pending_message": "Ihr Beitrag <strong>{entry}</strong> in <strong>{contest}</strong> ist eingegangen. Er ist noch nicht öffentlich: Er wird geprüft.",
        "participation_pending_note": "Den Status und jeden von Ihnen erwarteten Schritt können Sie in Ihren Einträgen verfolgen.",
        "participation_published_subject": "Ihr Beitrag ist veröffentlicht - MyHigh5",
        "participation_published_title": "Ihr Beitrag ist veröffentlicht",
        "participation_published_message": "Ihr Beitrag <strong>{entry}</strong> in <strong>{contest}</strong> ist jetzt auf MyHigh5 öffentlich sichtbar.",
        "participation_published_note": "Die Abstimmung beginnt, sobald der Wettbewerb seine Abstimmungsphase erreicht.",
        "participation_action_subject": "Aktualisierung Ihres Beitrags erforderlich - MyHigh5",
        "participation_action_title": "Für Ihren Beitrag ist eine Aktualisierung erforderlich",
        "participation_action_message": "Unser Team hat eine Aktualisierung Ihres Beitrags <strong>{entry}</strong> in <strong>{contest}</strong> angefordert. Er bleibt privat, bis er aktualisiert und erneut geprüft wurde.",
        "participation_action_note": "Öffnen Sie Ihre Einträge, um zu sehen, was benötigt wird, und aktualisieren Sie den Beitrag.",
        "participation_rejected_subject": "Ihr Beitrag wurde nicht angenommen - MyHigh5",
        "participation_rejected_title": "Ihr Beitrag wurde nicht angenommen",
        "participation_rejected_message": "Nach einer Prüfung durch unser Team wird Ihr Beitrag <strong>{entry}</strong> in <strong>{contest}</strong> nicht auf MyHigh5 angezeigt.",
        "participation_rejected_note": "Wenn Sie dies für einen Fehler halten, wenden Sie sich bitte an unseren Support.",
        "creative_unavailable_subject": "Ihr Videolink ist nicht mehr verfügbar - MyHigh5",
        "creative_unavailable_title": "Ihr Videolink ist nicht mehr verfügbar",
        "creative_unavailable_message": "Das mit <strong>{entry}</strong> in <strong>{contest}</strong> verknüpfte Video ist unter seiner Adresse nicht mehr auffindbar; der Eintrag wird daher nicht mehr auf MyHigh5 angezeigt.",
        "creative_unavailable_note": "Wenn das Video versehentlich verschoben oder auf privat gestellt wurde, wenden Sie sich bitte an unseren Support.",
        "kyc_action_subject": "Noch ein Schritt bis zum Abschluss Ihrer Verifizierung - MyHigh5",
        "kyc_action_title": "Noch ein Schritt bis zum Abschluss Ihrer Verifizierung",
        "kyc_action_message": "Ihre Identitätsprüfung war erfolgreich. Um Ihre Verifizierung abzuschließen, reichen Sie bitte einen Adressnachweis ein.",
        "kyc_action_button": "Verifizierung fortsetzen",
    },
}
