"""Add all MyHigh5 models

Revision ID: 002_add_myfav_models
Revises: 001_initial_migration
Create Date: 2025-08-27 16:25:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002_add_myfav_models'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create all ENUM types first (PostgreSQL doesn't support IF NOT EXISTS for CREATE TYPE)
    # Skip gender enum as it already exists from initial migration
    op.execute("DO $$ BEGIN CREATE TYPE seasonstatus AS ENUM ('UPCOMING', 'REGISTRATION_OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE stagelevel AS ENUM ('CITY', 'COUNTRY', 'REGION', 'CONTINENT', 'GLOBAL'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE stagestatus AS ENUM ('UPCOMING', 'REGISTRATION_OPEN', 'IN_PROGRESS', 'VOTING', 'COMPLETED'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE clubstatus AS ENUM ('ACTIVE', 'SUSPENDED', 'CLOSED'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE accounttype AS ENUM ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE userstatus AS ENUM ('ACTIVE', 'SUSPENDED', 'BANNED', 'PENDING_VERIFICATION'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    
    # Geography tables
    op.create_table('continents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=2), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code'),
        sa.UniqueConstraint('name')
    )
    
    op.create_table('regions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('continent_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=10), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['continent_id'], ['continents.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    op.create_table('countries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('region_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('code', sa.String(length=3), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    op.create_table('cities',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('country_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('state_province', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Contest tables
    op.create_table('contest_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    
    op.create_table('contest_categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contest_type_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('min_age', sa.Integer(), nullable=True),
        sa.Column('max_age', sa.Integer(), nullable=True),
        sa.Column('gender_restriction', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', 'ANY', name='gender'), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['contest_type_id'], ['contest_types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('contest_seasons',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('contest_type_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('registration_start', sa.DateTime(), nullable=False),
        sa.Column('registration_end', sa.DateTime(), nullable=False),
        sa.Column('status', postgresql.ENUM('UPCOMING', 'REGISTRATION_OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='seasonstatus'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['contest_type_id'], ['contest_types.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('contest_stages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('season_id', sa.Integer(), nullable=False),
        sa.Column('stage_type', postgresql.ENUM('CITY', 'COUNTRY', 'REGION', 'CONTINENT', 'GLOBAL', name='stagelevel'), nullable=False),
        sa.Column('geographic_entity_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('end_date', sa.DateTime(), nullable=False),
        sa.Column('voting_start', sa.DateTime(), nullable=False),
        sa.Column('voting_end', sa.DateTime(), nullable=False),
        sa.Column('max_participants', sa.Integer(), nullable=True),
        sa.Column('status', postgresql.ENUM('UPCOMING', 'REGISTRATION_OPEN', 'IN_PROGRESS', 'VOTING', 'COMPLETED', name='stagestatus'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['season_id'], ['contest_seasons.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    
    # DSP tables
    op.create_table('dsp_wallets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('balance_dsp', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('frozen_balance', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('total_earned', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('total_spent', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    
    # Affiliate tables
    op.create_table('affiliate_trees',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('sponsor_id', sa.Integer(), nullable=True),
        sa.Column('level', sa.Integer(), nullable=False),
        sa.Column('referral_code', sa.String(length=20), nullable=False),
        sa.Column('joined_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['sponsor_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('referral_code'),
        sa.UniqueConstraint('user_id')
    )
    
    # Fan clubs
    op.create_table('fan_clubs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('slug', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('membership_fee', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('premium_fee', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('annual_discount_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column('requires_approval', sa.Boolean(), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('max_members', sa.Integer(), nullable=True),
        sa.Column('multisig_threshold', sa.Integer(), nullable=True),
        sa.Column('status', postgresql.ENUM('ACTIVE', 'SUSPENDED', 'CLOSED', name='clubstatus'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    
    # Accounting tables
    op.create_table('chart_of_accounts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('account_code', sa.String(length=20), nullable=False),
        sa.Column('account_name', sa.String(length=200), nullable=False),
        sa.Column('account_type', postgresql.ENUM('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['chart_of_accounts.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('account_code')
    )

    # Update user table with new fields (note: table name is 'user' not 'users')
    op.add_column('user', sa.Column('continent_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('region_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('city_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=True))
    op.add_column('user', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('address_line1', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('address_line2', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('postal_code', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('identity_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('identity_verification_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('website_url', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('social_media_links', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('status', postgresql.ENUM('ACTIVE', 'SUSPENDED', 'BANNED', 'PENDING_VERIFICATION', name='userstatus'), nullable=True))
    
    # Add foreign key constraints for user
    op.create_foreign_key('fk_user_continent', 'user', 'continents', ['continent_id'], ['id'])
    op.create_foreign_key('fk_user_region', 'user', 'regions', ['region_id'], ['id'])
    op.create_foreign_key('fk_user_country', 'user', 'countries', ['country_id'], ['id'])
    op.create_foreign_key('fk_user_city', 'user', 'cities', ['city_id'], ['id'])
    
    # Create indexes
    op.create_index('ix_user_referral_code', 'user', ['referral_code'], unique=True)
    op.create_index('ix_contest_stages_geographic_entity', 'contest_stages', ['geographic_entity_id'])
    op.create_index('ix_affiliate_trees_sponsor', 'affiliate_trees', ['sponsor_id'])


def downgrade():
    # Drop indexes
    op.drop_index('ix_affiliate_trees_sponsor')
    op.drop_index('ix_contest_stages_geographic_entity')
    op.drop_index('ix_user_referral_code')
    
    # Drop foreign key constraints from user
    op.drop_constraint('fk_user_city', 'user', type_='foreignkey')
    op.drop_constraint('fk_user_country', 'user', type_='foreignkey')
    op.drop_constraint('fk_user_region', 'user', type_='foreignkey')
    op.drop_constraint('fk_user_continent', 'user', type_='foreignkey')
    
    # Remove columns from user
    op.drop_column('user', 'status')
    op.drop_column('user', 'social_media_links')
    op.drop_column('user', 'website_url')
    op.drop_column('user', 'profile_picture_url')
    op.drop_column('user', 'referral_code')
    op.drop_column('user', 'identity_verification_date')
    op.drop_column('user', 'identity_verified')
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'address_line2')
    op.drop_column('user', 'address_line1')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'date_of_birth')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'city_id')
    op.drop_column('user', 'country_id')
    op.drop_column('user', 'region_id')
    op.drop_column('user', 'continent_id')
    
    # Drop tables
    op.drop_table('chart_of_accounts')
    op.drop_table('fan_clubs')
    op.drop_table('affiliate_trees')
    op.drop_table('dsp_wallets')
    op.drop_table('contest_stages')
    op.drop_table('contest_seasons')
    op.drop_table('contest_categories')
    op.drop_table('contest_types')
    op.drop_table('cities')
    op.drop_table('countries')
    op.drop_table('regions')
    op.drop_table('continents')
    
    # Drop enums
    op.execute('DROP TYPE IF EXISTS userstatus')
    op.execute('DROP TYPE IF EXISTS accounttype')
    op.execute('DROP TYPE IF EXISTS clubstatus')
    op.execute('DROP TYPE IF EXISTS stagestatus')
    op.execute('DROP TYPE IF EXISTS stagelevel')
    op.execute('DROP TYPE IF EXISTS seasonstatus')
    op.execute('DROP TYPE IF EXISTS gender')
