"""Add contest_favorites table

Revision ID: 482a45496daf
Revises: 67cbb92aeac2
Create Date: 2025-11-13 16:52:22.871073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482a45496daf'
down_revision = '67cbb92aeac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('added_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contest_favorites_id'), 'contest_favorites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contest_favorites_id'), table_name='contest_favorites')
    op.drop_table('contest_favorites')
    # ### end Alembic commands ###
