"""Change video_media_id to video_media_ids JSON array

Revision ID: 533d3881e74e
Revises: 482a45496daf
Create Date: 2025-11-13 18:06:31.757830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533d3881e74e'
down_revision = '482a45496daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestants', sa.Column('video_media_ids', sa.String(length=1000), nullable=True))
    op.drop_column('contestants', 'video_media_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contestants', sa.Column('video_media_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('contestants', 'video_media_ids')
    # ### end Alembic commands ###
