"""Remove foreign key constraint from season_id

Revision ID: 67cbb92aeac2
Revises: 003_update_contestants
Create Date: 2025-11-13 15:48:23.388849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cbb92aeac2'
down_revision = '003_update_contestants'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE contestants
        DROP CONSTRAINT IF EXISTS contestants_season_id_fkey;
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'contestants_season_id_fkey'
            ) THEN
                ALTER TABLE contestants
                ADD CONSTRAINT contestants_season_id_fkey
                FOREIGN KEY (season_id) REFERENCES contest_seasons(id);
            END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###
