"""Remove foreign key constraint from season_id

Revision ID: 67cbb92aeac2
Revises: 003_update_contestants
Create Date: 2025-11-13 15:48:23.388849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67cbb92aeac2'
down_revision = '003_update_contestants'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contestants_season_id_fkey', 'contestants', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('contestants_season_id_fkey', 'contestants', 'contest_seasons', ['season_id'], ['id'])
    # ### end Alembic commands ###
