"""Add email_verified field to users

Revision ID: 81481e4ec1c8
Revises: add_preferred_language
Create Date: 2025-12-11 10:17:19.863138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81481e4ec1c8'
down_revision = 'add_preferred_language'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_verifications_status', table_name='user_verifications')
    op.drop_index('ix_user_verifications_user_id', table_name='user_verifications')
    op.drop_index('ix_user_verifications_user_type', table_name='user_verifications')
    op.drop_table('user_verifications')
    op.alter_column('contestant_verifications', 'verification_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('selfie', 'selfie_with_pet', 'selfie_with_doc', 'voice_recording', 'video_verification', 'brand_proof', name='contestantverificationtype'),
               existing_nullable=False)
    op.alter_column('contestant_verifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'approved', 'rejected', name='contestantverificationstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('ix_contestant_verifications_contestant_id', table_name='contestant_verifications')
    op.drop_index('ix_contestant_verifications_status', table_name='contestant_verifications')
    op.create_index(op.f('ix_contestant_verifications_id'), 'contestant_verifications', ['id'], unique=False)
    op.drop_constraint('deposits_reference_key', 'deposits', type_='unique')
    op.drop_index('ix_deposits_order_id', table_name='deposits')
    op.drop_index('ix_deposits_product_type_id', table_name='deposits')
    op.drop_index('ix_deposits_status', table_name='deposits')
    op.drop_index('ix_deposits_user_id', table_name='deposits')
    op.create_index(op.f('ix_deposits_id'), 'deposits', ['id'], unique=False)
    op.create_unique_constraint(None, 'deposits', ['order_id'])
    op.drop_constraint('deposits_user_id_fkey', 'deposits', type_='foreignkey')
    op.create_foreign_key(None, 'deposits', 'users', ['user_id'], ['id'])
    op.drop_column('deposits', 'payment_provider_id')
    op.drop_column('deposits', 'reference')
    op.alter_column('invitations', 'referral_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('invitations', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invitations', 'accepted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('invitations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('invitations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.drop_index('ix_invitations_inviter_id', table_name='invitations')
    op.drop_index('ix_invitations_referral_code', table_name='invitations')
    op.drop_index('ix_invitations_status', table_name='invitations')
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.drop_constraint('invitations_invited_user_id_fkey', 'invitations', type_='foreignkey')
    op.drop_constraint('invitations_inviter_id_fkey', 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'users', ['inviter_id'], ['id'])
    op.create_foreign_key(None, 'invitations', 'users', ['invited_user_id'], ['id'])
    op.create_unique_constraint(None, 'kyc_verifications', ['user_id'])
    op.create_index(op.f('ix_payment_methods_id'), 'payment_methods', ['id'], unique=False)
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_product_types_id'), 'product_types', ['id'], unique=False)
    op.drop_index('ix_role_id', table_name='roles')
    op.drop_index('ix_role_name', table_name='roles')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.drop_index('ix_users_sponsor_id', table_name='users')
    op.drop_constraint('users_sponsor_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['sponsor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_sponsor_id_fkey', 'users', 'users', ['sponsor_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_users_sponsor_id', 'users', ['sponsor_id'], unique=False)
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_index('ix_role_name', 'roles', ['name'], unique=False)
    op.create_index('ix_role_id', 'roles', ['id'], unique=False)
    op.drop_index(op.f('ix_product_types_id'), table_name='product_types')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_payment_methods_id'), table_name='payment_methods')
    op.drop_constraint(None, 'kyc_verifications', type_='unique')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key('invitations_inviter_id_fkey', 'invitations', 'users', ['inviter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('invitations_invited_user_id_fkey', 'invitations', 'users', ['invited_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.create_index('ix_invitations_status', 'invitations', ['status'], unique=False)
    op.create_index('ix_invitations_referral_code', 'invitations', ['referral_code'], unique=False)
    op.create_index('ix_invitations_inviter_id', 'invitations', ['inviter_id'], unique=False)
    op.alter_column('invitations', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('invitations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invitations', 'expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('invitations', 'accepted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('invitations', 'sent_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invitations', 'referral_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.add_column('deposits', sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('deposits', sa.Column('payment_provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deposits', type_='foreignkey')
    op.create_foreign_key('deposits_user_id_fkey', 'deposits', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'deposits', type_='unique')
    op.drop_index(op.f('ix_deposits_id'), table_name='deposits')
    op.create_index('ix_deposits_user_id', 'deposits', ['user_id'], unique=False)
    op.create_index('ix_deposits_status', 'deposits', ['status'], unique=False)
    op.create_index('ix_deposits_product_type_id', 'deposits', ['product_type_id'], unique=False)
    op.create_index('ix_deposits_order_id', 'deposits', ['order_id'], unique=False)
    op.create_unique_constraint('deposits_reference_key', 'deposits', ['reference'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_contestant_verifications_id'), table_name='contestant_verifications')
    op.create_index('ix_contestant_verifications_status', 'contestant_verifications', ['status'], unique=False)
    op.create_index('ix_contestant_verifications_contestant_id', 'contestant_verifications', ['contestant_id'], unique=False)
    op.alter_column('contestant_verifications', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', name='contestantverificationstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('contestant_verifications', 'verification_type',
               existing_type=sa.Enum('selfie', 'selfie_with_pet', 'selfie_with_doc', 'voice_recording', 'video_verification', 'brand_proof', name='contestantverificationtype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_table('user_verifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('verification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('media_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('media_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contest_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contestant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], name='user_verifications_contest_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contestant_id'], ['contestants.id'], name='user_verifications_contestant_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='user_verifications_reviewed_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_verifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_verifications_pkey')
    )
    op.create_index('ix_user_verifications_user_type', 'user_verifications', ['user_id', 'verification_type'], unique=False)
    op.create_index('ix_user_verifications_user_id', 'user_verifications', ['user_id'], unique=False)
    op.create_index('ix_user_verifications_status', 'user_verifications', ['status'], unique=False)
    # ### end Alembic commands ###
