"""Add position field to MyFavorites

Revision ID: bfd38b158b18
Revises: 88224b7bb153
Create Date: 2025-11-17 10:49:43.541397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd38b158b18'
down_revision = '88224b7bb153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists before adding it
    op.execute("""
        DO $$ 
        BEGIN 
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'my_favorites' AND column_name = 'position'
            ) THEN
                ALTER TABLE my_favorites ADD COLUMN position INTEGER DEFAULT 0 NOT NULL;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_favorites', 'position')
    # ### end Alembic commands ###
