"""Add position field to MyFavorites

Revision ID: bfd38b158b18
Revises: 88224b7bb153
Create Date: 2025-11-17 10:49:43.541397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd38b158b18'
down_revision = '88224b7bb153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('my_favorites', sa.Column('position', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('my_favorites', 'position')
    # ### end Alembic commands ###
