"""Update comment model to use contestant_id

Revision ID: d663619d4a51
Revises: bfd38b158b18
Create Date: 2025-11-17 19:04:26.312265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd663619d4a51'
down_revision = 'bfd38b158b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('contestant_id', sa.Integer(), nullable=True))
    op.drop_constraint('comment_contest_entry_id_fkey', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'contestants', ['contestant_id'], ['id'])
    op.drop_column('comment', 'contest_entry_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('contest_entry_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_contest_entry_id_fkey', 'comment', 'contest_entry', ['contest_entry_id'], ['id'])
    op.drop_column('comment', 'contestant_id')
    # ### end Alembic commands ###
