"""add_notifications_table

Revision ID: d7831cdf8d92
Revises: add_reactions_shares
Create Date: 2025-12-01 15:44:59.589696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd7831cdf8d92'
down_revision = 'add_reactions_shares'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SYSTEM', 'CONTEST', 'COMPTE', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_contestant_id', sa.Integer(), nullable=True),
    sa.Column('related_comment_id', sa.Integer(), nullable=True),
    sa.Column('related_contest_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['related_comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['related_contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['related_contestant_id'], ['contestants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index('ix_admin_contests_id', table_name='admin_contests')
    op.drop_table('admin_contests')
    op.alter_column('contest', 'voting_restriction',
               existing_type=postgresql.ENUM('NONE', 'MALE_ONLY', 'FEMALE_ONLY', 'GEOGRAPHIC', 'AGE_RESTRICTED', name='votingrestriction'),
               nullable=False,
               existing_server_default=sa.text("'NONE'::votingrestriction"))
    op.drop_index('ix_contest_season_links_contest_id', table_name='contest_season_links')
    op.drop_index('ix_contest_season_links_season_id', table_name='contest_season_links')
    op.create_index(op.f('ix_contest_season_links_id'), 'contest_season_links', ['id'], unique=False)
    op.drop_index('uq_contest_seasons_level_active', table_name='contest_seasons', postgresql_where='(is_deleted = false)')
    op.drop_index('ix_contestant_reactions_contestant_id', table_name='contestant_reactions')
    op.drop_index('ix_contestant_reactions_user_id', table_name='contestant_reactions')
    op.drop_constraint('uq_user_contestant_reaction', 'contestant_reactions', type_='unique')
    op.create_index(op.f('ix_contestant_reactions_id'), 'contestant_reactions', ['id'], unique=False)
    op.drop_index('ix_contestant_seasons_contestant_id', table_name='contestant_seasons')
    op.drop_index('ix_contestant_seasons_season_id', table_name='contestant_seasons')
    op.create_index(op.f('ix_contestant_seasons_id'), 'contestant_seasons', ['id'], unique=False)
    op.drop_index('ix_contestant_shares_contestant_id', table_name='contestant_shares')
    op.drop_index('ix_contestant_shares_user_id', table_name='contestant_shares')
    op.create_index(op.f('ix_contestant_shares_id'), 'contestant_shares', ['id'], unique=False)
    op.drop_constraint('fk_contestants_contest_id', 'contestants', type_='foreignkey')
    op.drop_column('contestants', 'contest_id')
    op.drop_constraint('like_contest_entry_id_fkey', 'like', type_='foreignkey')
    op.drop_column('like', 'contest_entry_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('like', sa.Column('contest_entry_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('like_contest_entry_id_fkey', 'like', 'contest_entry', ['contest_entry_id'], ['id'])
    op.add_column('contestants', sa.Column('contest_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_contestants_contest_id', 'contestants', 'contest', ['contest_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_contestant_shares_id'), table_name='contestant_shares')
    op.create_index('ix_contestant_shares_user_id', 'contestant_shares', ['user_id'], unique=False)
    op.create_index('ix_contestant_shares_contestant_id', 'contestant_shares', ['contestant_id'], unique=False)
    op.drop_index(op.f('ix_contestant_seasons_id'), table_name='contestant_seasons')
    op.create_index('ix_contestant_seasons_season_id', 'contestant_seasons', ['season_id'], unique=False)
    op.create_index('ix_contestant_seasons_contestant_id', 'contestant_seasons', ['contestant_id'], unique=False)
    op.drop_index(op.f('ix_contestant_reactions_id'), table_name='contestant_reactions')
    op.create_unique_constraint('uq_user_contestant_reaction', 'contestant_reactions', ['user_id', 'contestant_id'], postgresql_nulls_not_distinct=False)
    op.create_index('ix_contestant_reactions_user_id', 'contestant_reactions', ['user_id'], unique=False)
    op.create_index('ix_contestant_reactions_contestant_id', 'contestant_reactions', ['contestant_id'], unique=False)
    op.create_index('uq_contest_seasons_level_active', 'contest_seasons', ['level'], unique=False, postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('ix_contest_season_links_id'), table_name='contest_season_links')
    op.create_index('ix_contest_season_links_season_id', 'contest_season_links', ['season_id'], unique=False)
    op.create_index('ix_contest_season_links_contest_id', 'contest_season_links', ['contest_id'], unique=False)
    op.alter_column('contest', 'voting_restriction',
               existing_type=postgresql.ENUM('NONE', 'MALE_ONLY', 'FEMALE_ONLY', 'GEOGRAPHIC', 'AGE_RESTRICTED', name='votingrestriction'),
               nullable=True,
               existing_server_default=sa.text("'NONE'::votingrestriction"))
    op.create_table('admin_contests',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contest_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('level', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_submission_open', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_voting_open', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('submission_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('submission_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('voting_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('voting_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('voting_restriction', postgresql.ENUM('NONE', 'MALE_ONLY', 'FEMALE_ONLY', 'GEOGRAPHIC', 'AGE_RESTRICTED', name='votingrestriction'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admin_contests_pkey')
    )
    op.create_index('ix_admin_contests_id', 'admin_contests', ['id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
