"""Add text fields for user location

Revision ID: f9e6829e1555
Revises: 9b4a6c5f98a7
Create Date: 2025-11-12 18:05:20.000394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e6829e1555'
down_revision = '9b4a6c5f98a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    insp = sa.inspect(bind)

    def has_table(name: str) -> bool:
        return name in insp.get_table_names()

    def has_column(table: str, column: str) -> bool:
        if not has_table(table):
            return False
        return column in {c["name"] for c in insp.get_columns(table)}

    if has_table('continents') and has_column('continents', 'code'):
        op.alter_column('continents', 'code',
                   existing_type=sa.VARCHAR(length=10),
                   nullable=True)
    if has_table('countries') and has_column('countries', 'code'):
        op.alter_column('countries', 'code',
                   existing_type=sa.VARCHAR(length=3),
                   nullable=True)
    if has_table('regions') and has_column('regions', 'code'):
        op.alter_column('regions', 'code',
                   existing_type=sa.VARCHAR(length=10),
                   nullable=True)
    if has_table('users'):
        if not has_column('users', 'continent'):
            op.add_column('users', sa.Column('continent', sa.String(length=100), nullable=True))
        if not has_column('users', 'region'):
            op.add_column('users', sa.Column('region', sa.String(length=100), nullable=True))
        if not has_column('users', 'country'):
            op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
        if not has_column('users', 'city'):
            op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    op.drop_column('users', 'region')
    op.drop_column('users', 'continent')
    op.alter_column('regions', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('countries', 'code',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('continents', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
