/** Maps user country labels to regional voting pool names (same pool as contest list navigation). */
export const REGIONAL_POOL_BY_COUNTRY: Record<string, string> = {
  tanzania: "East Africa",
  tz: "East Africa",
  kenya: "East Africa",
  ke: "East Africa",
  uganda: "East Africa",
  ug: "East Africa",
  rwanda: "East Africa",
  rw: "East Africa",
  burundi: "East Africa",
  bi: "East Africa",
  ethiopia: "East Africa",
  et: "East Africa",
  somalia: "East Africa",
  so: "East Africa",
  eritrea: "East Africa",
  er: "East Africa",
  djibouti: "East Africa",
  dj: "East Africa",
  "south sudan": "East Africa",
  ss: "East Africa",
  sudan: "East Africa",
  sd: "East Africa",
  nigeria: "West Africa",
  ng: "West Africa",
  ghana: "West Africa",
  gh: "West Africa",
  senegal: "West Africa",
  sn: "West Africa",
  "ivory coast": "West Africa",
  "cote d'ivoire": "West Africa",
  "côte d'ivoire": "West Africa",
  ci: "West Africa",
  "south africa": "Southern Africa",
  za: "Southern Africa",
  zimbabwe: "Southern Africa",
  zw: "Southern Africa",
  zambia: "Southern Africa",
  zm: "Southern Africa",
  botswana: "Southern Africa",
  bw: "Southern Africa",
  namibia: "Southern Africa",
  na: "Southern Africa",
  mozambique: "Southern Africa",
  mz: "Southern Africa",
  malawi: "Southern Africa",
  mw: "Southern Africa",
  angola: "Southern Africa",
  ao: "Southern Africa",
  egypt: "North Africa",
  eg: "North Africa",
  morocco: "North Africa",
  ma: "North Africa",
  algeria: "North Africa",
  dz: "North Africa",
  tunisia: "North Africa",
  tn: "North Africa",
  libya: "North Africa",
  ly: "North Africa",
  cameroon: "Central Africa",
  cm: "Central Africa",
  "democratic republic of the congo": "Central Africa",
  drc: "Central Africa",
  cd: "Central Africa",
  "republic of the congo": "Central Africa",
  cg: "Central Africa",
  gabon: "Central Africa",
  ga: "Central Africa",
  chad: "Central Africa",
  td: "Central Africa",
}

export function regionalPoolForCountry(country?: string | null): string | undefined {
  const key = country?.trim().toLowerCase()
  return key ? REGIONAL_POOL_BY_COUNTRY[key] : undefined
}
